### ISSUE TITLE
 403 error

### ISSUE THREAD

**Issue by sd031** [radiegtya/meteoris-v1#1]
hi , I am unable to add custom route other then insert , update , delete (CRUDS) , all the time showing 403 access forbidden error .

Please help me out .

**Comment by radiegtya** [comment]
have you edit the role action at mugen role action menu?

**Comment by sd031** [comment]
that , issue solved by allowing that menu action , but is there a way to allow all action by all users (guest , authenticated user or user with any role ) , by default (so I don't have to use that mugen role action menu .)

**Comment by sd031** [comment]
I figured it out.
